[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = .
timeout = 2
norecursedirs = .git .hg .tox dist build venv .venv __pycache__ node_modules manual
filterwarnings =
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
    ignore:The `update_forward_refs` method is deprecated:DeprecationWarning
