from setuptools import setup, find_packages

setup(
    name="sage",
    version="0.9.2",
    description="A production-ready, modular, and intelligent multi-agent orchestration framework for complex problem solving.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Eric ZZ",
    author_email="",
    url="https://github.com/ZHangZHengEric/Sage",
    license="MIT",
    packages=find_packages(include=["sagents*"], exclude=["tests*", "examples*", "docs*", "assets*", "logs*"]),
    include_package_data=True,
    install_requires=[
        "gradio>=4.0.0",
        "openai>=1.0.0",
        "requests>=2.31.0",
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0",
        "aiofiles>=0.8.0",
        "fastapi>=0.104.0",
        "uvicorn[standard]>=0.24.0",
        "websockets>=12.0",
        "pydantic>=2.5.0",
        "mcp>=1.9.2",
        "fastmcp>=0.9.0",
        "docstring_parser>=0.16",
        "chardet>=5.0.0",
        "httpx>=0.24.0",
        "pdfplumber",
        "html2text",
        "openpyxl",
        "pypandoc",
        "python-docx",
        "markdown",
        "python-pptx",
        "PyMuPDF",
        "tqdm",
        "unstructured"
    ],
    python_requires=">=3.10",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
) 