apiVersion: 1

# Create missing data sources, but leave existing ones unchanged.
datasources:
  - name: Sage Prometheus
    uid: sage-prometheus
    type: prometheus
    access: proxy
    url: http://sage-prometheus:9090
    isDefault: true
    version: -1
    editable: true

  - name: Sage Loki
    uid: sage-loki
    type: loki
    access: proxy
    url: http://sage-loki:3100
    version: -1
    editable: true

  - name: Sage Jaeger
    uid: sage-jaeger
    type: jaeger
    access: proxy
    url: http://sage-jaeger:16686
    version: -1
    editable: true
