"""Optional diagnostics and tracing sinks."""

from sagents.v2.runtime.observability.contracts import (
    DiagnosticSink,
    LogError,
    LogLevel,
    LogRecord,
    LogSink,
    TraceEvent,
    TraceKind,
    TraceSink,
    TraceSpan,
    TraceStatus,
)
from sagents.v2.runtime.observability.logs import (
    StructuredLogger,
    StructuredLoggingHandler,
    encode_log_record,
    install_standard_logging,
    redact_log_value,
)
from sagents.v2.runtime.observability.plugins import (
    FilesystemDiagnosticSink,
    FilesystemLogSink,
    NoopDiagnosticSink,
    NoopLogSink,
    NoopTraceSink,
    OtlpTraceSink,
    StdoutLogSink,
    otel_available,
)
from sagents.v2.runtime.observability.traces import (
    SpanHandle,
    StructuredTracer,
    current_trace_context,
    preview_trace_value,
    resolve_root_session_id,
    session_trace_id,
)

__all__ = [
    "DiagnosticSink",
    "FilesystemDiagnosticSink",
    "FilesystemLogSink",
    "StdoutLogSink",
    "LogError",
    "LogLevel",
    "LogRecord",
    "LogSink",
    "NoopDiagnosticSink",
    "NoopLogSink",
    "NoopTraceSink",
    "OtlpTraceSink",
    "SpanHandle",
    "StructuredLogger",
    "StructuredLoggingHandler",
    "StructuredTracer",
    "current_trace_context",
    "preview_trace_value",
    "resolve_root_session_id",
    "session_trace_id",
    "TraceEvent",
    "TraceKind",
    "TraceSink",
    "TraceSpan",
    "TraceStatus",
    "encode_log_record",
    "install_standard_logging",
    "otel_available",
    "redact_log_value",
]
