from typing import Dict, List
from sagents.tool.tool_base import tool
from sagents.utils.logger import logger


class FibreTools:
    """
    System-level tools for Fibre Agents.
    """

    @tool(
        description_i18n={"zh": "创建一个新的子智能体（专家角色）。注意：创建的必须是具备通用能力的领域专家（如'Python专家'），而不是针对当前具体任务的一次性执行者（如'贪吃蛇编写者'）。"},
        param_description_i18n={
            "name": {"zh": "智能体的拟人化昵称（花名），例如，'乔巴'或'Eric'，用于显示和交互。请选择自然、亲切的人名风格，避免使用专业术语（如'Python专家'）。"},
            "description": {"zh": "智能体的职能描述。**必须**定义为一类通用的专业能力（如'Python编程专家'），**严禁**描述为具体的单一任务（如'写贪吃蛇代码'）。"},
            "system_prompt": {"zh": "智能体的详细系统设定（Persona）。为了确保子智能体表现出高水平的专业能力，**System Prompt 必须详尽且结构化，字数不得少于300字**。请严格按照以下结构编写：\n1. **角色定义**：清晰定义专家的身份、背景及核心职责（如'资深Python架构师，拥有10年分布式系统开发经验...'）。\n2. **能力范围**：列举其精通的技术栈、解决的问题类型及专业技能。\n3. **行为偏好**：规定其思维方式、代码风格（如'追求极致性能'、'遵循PEP8'）及沟通习惯。\n4. **限制与约束**：明确其不应做的事情及伦理边界。\n**注意**：System Prompt 仅用于定义角色属性，**严禁**包含具体的任务指令（如'写贪吃蛇'），具体任务请在 `sys_delegate_task` 中下发。"}
        }
    )
    async def sys_spawn_agent(self, name: str, description: str, system_prompt: str, session_id: str = "") -> str:
        """
        Create a new sub-agent.

        Args:
            name: Human-readable nickname (a warm, real-person name like "乔巴" or "Eric") for display. Must match the conversation language:
            description: Short summary of the agent's role (should describe a class of tasks)
            system_prompt: The System Prompt defining the agent's persona, capabilities, and constraints
            session_id: The current session ID (auto-injected)
        """
        logger.info(f"Tool Call: sys_spawn_agent(name={name}, description={description})")

        from sagents.session_runtime import get_global_session_manager
        session_manager = get_global_session_manager()
        session = session_manager.get(session_id)
        if not session:
            return f"Error: Session not found for session_id: {session_id}"
        session_context = session.session_context
        orchestrator = getattr(session_context, "orchestrator", None)
        if not orchestrator:
             return "Error: Orchestrator not found in session context."

        # New architecture: pass parent_session_id instead of parent_context
        # agent_id will be auto-generated by spawn_agent based on backend availability
        new_agent_id = await orchestrator.spawn_agent(
            parent_session_id=session_id,
            name=name,
            description=description,
            system_prompt=system_prompt
        )
        return f"Agent spawned successfully. ID: {new_agent_id}. Ready to receive messages."

    @tool(
        description_i18n={"zh": "给子agent 分配具体任务并执行，tasks 列表中的任务是并发执行的。可以给同一个 agent 委派两个并行的任务，它们会同时执行（需要使用不同的 session_id）。如果有前后顺序依赖的任务，应该分两次调用本工具，先执行前置任务，再执行后置任务。具体任务细节（如'写贪吃蛇'）应在这里通过 content 指定。"},
        param_description_i18n={
            "tasks": {"zh": "任务列表，每个任务包含 'agent_id', 'content' 等字段。'content' 必须包含详细的具体任务描述、上下文信息、具体要求以及期望的返回格式。'session_id' 为可选项，仅在需要继续之前的会话时才填写。注意：列表中的任务是并发执行的，可以给同一个 agent 分配多个并行任务（需使用不同的 session_id），如果有依赖关系请分多次调用。"}
        },
        param_schema={
            "tasks": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "agent_id": {
                            "type": "string",
                            "description": "The target agent ID to delegate the task to (e.g., 'python_expert_1').",
                            "description_i18n": {"zh": "目标子智能体ID（例如 'python_expert_1'）。"}
                        },
                        "task_name": {
                            "type": "string",
                            "description": "A unique identifier for the task (e.g., 'task_write_snake').",
                            "description_i18n": {"zh": "任务的唯一标识符（例如 'task_write_snake'）。用于后续查询任务状态或结果。"}
                        },
                        "original_task": {
                            "type": "string",
                            "description": "The original task description provided by the user.",
                            "description_i18n": {"zh": "最初的任务初衷，用于记录和跟踪任务的原始需求。"}
                        },
                        "content": {
                            "type": "string",
                            "description": "Detailed task description, context, requirements, and expected return format.",
                            "description_i18n": {"zh": "详细的子任务描述、上下文信息、具体要求以及期望的返回格式。"}
                        },
                        "session_id": {
                            "type": "string",
                            "description": "Optional: Session ID to continue an existing conversation. Leave empty to create a new session.",
                            "description_i18n": {"zh": "可选：如需继续之前的会话，请填写已有的 Session ID；如为新任务，请留空，系统会自动创建新会话。"}
                        }
                    },
                    "required": ["agent_id", "task_name", "original_task", "content"]
                }
            }
        }
    )
    async def sys_delegate_task(self, tasks: List[Dict[str, str]], session_id: str = "") -> str:
        """
        Delegate tasks to existing sub-agents and wait for the results. Supports parallel execution.

        Args:
            tasks: A list of tasks, where each task is a dictionary containing 'agent_id', 'content', and optionally 'session_id'.
                   'session_id' is optional and only needed when continuing an existing conversation.
                   'content' should be detailed and specify exactly what information needs to be returned via sys_finish_task.
            session_id: The current session ID (auto-injected)
        """
        logger.info(f"Tool Call: sys_delegate_task(tasks_count={len(tasks)})")
        
        from sagents.session_runtime import get_global_session_manager
        session_manager = get_global_session_manager()
        session = session_manager.get(session_id)
        if not session:
            return f"Error: Session not found for session_id: {session_id}"
        session_context = session.session_context
        orchestrator = getattr(session_context, "orchestrator", None)
        if not orchestrator:
             return "Error: Orchestrator not found in session context."

        response = await orchestrator.delegate_tasks(tasks, caller_session_id=session_id)
        return response

    @tool(
        description_i18n={
            "zh": "向父节点报告任务执行的最终结果。当子智能体完成所有任务后，使用此工具提交详细的执行结果和总结。",
            "en": "Report the final result of task execution to the parent agent. Use this tool when the sub-agent has completed all tasks to submit detailed execution results and summary."
        },
        param_description_i18n={
            "status": {
                "zh": "任务执行状态，可选值：'success'（成功）或 'failed'（失败）",
                "en": "Task execution status, options: 'success' or 'failed'"
            },
            "result": {
                "zh": "任务执行的详细结果总结。必须包含：1) 执行过程的关键步骤；2) 生成的资源文件路径；3) 数据分析结论；4) 建议或后续行动。支持 Markdown 格式，可以包含表格、列表等结构化内容。",
                "en": "Detailed summary of task execution results. Must include: 1) Key execution steps; 2) Generated resource file paths; 3) Data analysis conclusions; 4) Recommendations or follow-up actions. Supports Markdown format with tables, lists, etc."
            }
        }
    )
    async def sys_finish_task(self, status: str, result: str) -> str:
        """
        Report final result to parent.

        Args:
            status: Task status (success/failed)
            result: The detailed final result. Must include all information requested by the parent agent, 
                    including key execution steps, paths to generated resources, and specific conclusions.
        """
        # This is typically called by the sub-agent, not the parent.
        # But if the parent calls it, it ends the main session?
        return f"Task finished: {status}. Result had been reported to parent agent."
