#!/bin/bash

echo "🔑 AList 访问信息"
echo "========================================"
echo "🌐 Web 界面: http://localhost:20045"
echo "👤 管理员账号: admin"
echo "🔐 管理员密码: sage123456"
echo ""
echo "✅ 存储配置状态:"
echo "   本地存储已自动配置完成"
echo "   游客访问权限已开启"
echo "   可以直接访问文件（无需登录）"
echo ""
echo "📁 工作空间映射:"
echo "   本地: /srv/sage_demo_workspace"
echo "   AList: 根目录 /"
echo ""
echo "🎯 如何访问:"
echo "   1. 直接访问: http://localhost:20045"
echo "   2. 无需登录即可浏览文件"
echo "   3. 管理员登录可进行高级设置"
echo ""
echo "🔧 管理操作:"
echo "   查看容器日志: docker compose logs sage_alist"
echo "   重置密码: docker compose exec sage_alist ./alist admin set 新密码 --data /opt/alist/data"
echo "   重启服务: docker compose restart sage_alist"
echo "   重新配置存储: ./setup-alist-storage.sh"
echo ""
echo "💡 提示: 如果登录时提示 'storage not found'，请运行:"
echo "   ./setup-alist-storage.sh" 