global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - sage-prometheus:9090

  - job_name: sage-server
    metrics_path: /api/observability/metrics
    static_configs:
      - targets:
          - sage-server:8080

  - job_name: sage-server-dev
    metrics_path: /api/observability/metrics
    static_configs:
      - targets:
          - sage-server-dev:8080

  - job_name: sage-server-test
    metrics_path: /api/observability/metrics
    static_configs:
      - targets:
          - sage-server-test:8080

  - job_name: docker-containers
    static_configs:
      - targets:
          - sage-cadvisor:8080
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        regex: (.+)
        target_label: job
        replacement: $1
